name: PR Code Quality Check

# Trigger this workflow ONLY on pull requests to any branch
on:
  pull_request:

jobs:
  code-quality:
    name: Check Code Formatting and Build
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # 1. Checkout the code from the pull request
      - name: Checkout Code
        uses: actions/checkout@v4  # Or a specific stable version like @v3

      # 2. Setup the .NET SDK environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4  # Or a specific stable version like @v3
        with:
          dotnet-version: '8.x'  # Adjust to your project's .NET version (e.g., '6.x', '7.x')

      # 3. Restore .NET dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # 4. Run your code quality commands
      - name: Run Format Check and Build
        run: |
          dotnet format --verify-no-changes
          dotnet build --configuration Release --verbosity normal
